import = ["~..config/alacritty/themes/themes/tomorrow_night_bright.yaml"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_timeout = 5
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"

[font.normal]
family = "monospace"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[window.position]
x = 0
y = 0
